name: 'ms-teams-action'
description: 'action for ms teams'
author: 'chrisyates-sage'
inputs:
  message:
    description: 'Message'
    required: false
    default: Test started from ${{ github.event_name }}
runs:
  using: 'node12'
  main: 'index.js'
